import { NextResponse } from "next/server";
import { buildIcs } from "@/lib/ics";

// Public calendar feed (was a static cal.ics regenerated by update_ics.php;
// now generated on demand, so it can never go stale).
export const dynamic = "force-dynamic";

export async function GET() {
  const ics = await buildIcs();
  return new NextResponse(ics, {
    headers: {
      "Content-Type": "text/calendar; charset=utf-8",
      "Content-Disposition": 'inline; filename="cal.ics"',
    },
  });
}
